version: '3.8'

services:
  # --- 1. BANCO DE DADOS ---
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ESTOQUE}
      MYSQL_DATABASE: api_estoque
    command: --innodb-buffer-pool-size=64M
    volumes:
      - db_data:/var/lib/mysql

  # --- 2. APLICAÇÃO JAVA ---
  app:
    build: .
    restart: always
    # NOTA: Não expomos a porta "8080" para fora.
    # Apenas o Nginx consegue falar com ela internamente.
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/api_estoque?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS_ESTOQUE}
      JWT_SECRET_ESTOQUE: ${JWT_SECRET_ESTOQUE}
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx350m"
    depends_on:
      - mysqldb

  # --- 3. NGINX (NOVO) ---
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data: