version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ESTOQUE}
      MYSQL_DATABASE: api_estoque
    command: --innodb-buffer-pool-size=64M
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/api_estoque?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS_ESTOQUE}
      JWT_SECRET_ESTOQUE: ${JWT_SECRET_ESTOQUE}
      # Novas vari√°veis de Email
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx350m"
    depends_on:
      - mysqldb

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:

      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/jdb-site:/usr/share/nginx/html/landing:ro

    depends_on:
      - app

volumes:
